### ISSUE TITLE
segfault on run when template is being cloned

### ISSUE THREAD

**Issue by dahabakuk** [Oxalide/vsphere-influxdb-go#44]
hi,

first of all, great work!

im quite happy with your tool but i encouter an issue on a regular basis:

we use templates in our infrastructure which get deployed as vms.

whenever such a deployment is run, vsphere-influxdb-go segfaults with the following error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x918f98]

goroutine 1 [running]:
main.(*VCenter).Query(0xc420379b98, 0xc4200d04a0, 0x1, 0x4, 0xc4200f0180, 0x4, 0x4, 0x3c, 0xc4200167c0, 0x10, ...)
        /home/travis/gopath/src/github.com/Oxalide/vsphere-influxdb-go/vsphere-influxdb.go:387 +0x2cc8
main.queryVCenter(0xc420014420, 0x17, 0xc420014400, 0x16, 0xc420016850, 0xe, 0xc4204dfbe0, 0x3, 0x4, 0xc4200d04a0, ...)
        /home/travis/gopath/src/github.com/Oxalide/vsphere-influxdb-go/vsphere-influxdb.go:742 +0xf2
main.main()
        /home/travis/gopath/src/github.com/Oxalide/vsphere-influxdb-go/vsphere-influxdb.go:812 +0x7ef

**Comment by sofixa** [comment]
Hi, @dahabakuk . Yep, it's a known issue, since clone-in-progress appear as VMs, but lack all of the VM properties. I'll try to find a workaround and will post a fix soon.

Cheers,
Adrian

**Comment by sofixa** [comment]
@dahabakuk Could you try [0.8.2](https://github.com/Oxalide/vsphere-influxdb-go/releases/tag/v0.8.2) ? It should fix the segfaults and, if you have multiple vCenters, result in a substantial speed increase. 

Cheers,
Adrian

**Comment by dahabakuk** [comment]
hi,

still having problems:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x919aec]

goroutine 21 [running]:
main.(*VCenter).Query(0xc420074690, 0xc4200d8480, 0x3, 0x4, 0xc4200fa180, 0x4, 0x4, 0x3c, 0xc4200167d0, 0x2, ...)
        /home/travis/gopath/src/github.com/Oxalide/vsphere-influxdb-go/vsphere-influxdb.go:452 +0x35ac
main.worker(0x3, 0xc4200d8480, 0x3, 0x4, 0xc4200fa180, 0x4, 0x4, 0x3c, 0xc4200167d0, 0x2, ...)
        /home/travis/gopath/src/github.com/Oxalide/vsphere-influxdb-go/vsphere-influxdb.go:771 +0x2c0
created by main.main
        /home/travis/gopath/src/github.com/Oxalide/vsphere-influxdb-go/vsphere-influxdb.go:858 +0x84a


br

**Comment by sofixa** [comment]
Sorry, @dahabakuk , missed one bit, that should be fixed in [0.8.3](https://github.com/Oxalide/vsphere-influxdb-go/releases/tag/v0.8.3) . 

Adrian

**Comment by dahabakuk** [comment]
0.8.3 fixes this!
thanks alot!
